### ISSUE TITLE
Cannot find 'Type<SpeechRecognition> 🐞 

### ISSUE THREAD

**Issue by RaimonxDev** [taiga-family/ng-web-apis#279]
### Description

I have the same problem but angular version 17
https://github.com/taiga-family/ng-web-apis/issues/116

. any solution?  
![image](https://github.com/taiga-family/ng-web-apis/assets/39868803/7527c9d9-0c2b-4294-9ab8-e14aa067a69e)

Version: 
```
"@ng-web-apis/common": "^3.0.6",
"@ng-web-apis/speech": "^3.0.7",
"@angular/common": "17.0.2",
"@angular/compiler": "17.0.2",
"@angular/core": "17.0.2",
```

### Angular version

17.0.2

### Taiga UI version

3.0.6

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by lucbu01** [comment]
I had the same issue. Yarn told me to install `@types/dom-speech-recognition`.
<img width="588" alt="2023-11-13 09_59_03-package json - pta-prototype - Visual Studio Code" src="https://github.com/taiga-family/ng-web-apis/assets/35363738/6a3d4e4c-e1de-4cd8-8b23-14d55cea664d">

After add this to `compilerOptions` in `tsconfig.json` and make sure that theese options are not overridden in `tsconfig.app.json` it worked for me:
```json
    "typeRoots": ["node_modules/@types"],
    "types": ["node", "dom-speech-recognition"],
```

**Comment by waterplea** [comment]
Modern `npm` should automatically resolve peer deps, if you use a tool that does not do it on its own (`yarn`, apparently 🙂) — you should do it yourself, that's what peer deps are all about. Thank you for suggesting how to do it 👍
