### ISSUE TITLE
🚀 -  Pass intersection observer to observer handler

### ISSUE THREAD

**Issue by winston0410** [taiga-family/ng-web-apis#523]
### Description

At the moment, only entries is passed to the event handler: https://github.com/taiga-family/ng-web-apis/blob/1c94f4f07429f4d5abd2004d81cd38d0b9fd727b/libs/intersection-observer/src/services/intersection-observee.service.ts#L14

I have a use case where I want to only trigger the callback function once, and a simple way to achieve this would be calling `observer.unsubscribe()`. But at the moment, only `entries` are passed to the subscriber, and there is no way to access the `observer`. It would be great if `observer` can be passed to the subscriber too.

**Comment by waterplea** [comment]
Hi @winston0410, here's how you can pass the observer to the callback yourself, currently:
https://stackblitz.com/edit/angular-j1k6g5
Basically `waIntersectionObserver` directive IS the `IntersectionObserver`. So you can access it any way you like, either via template reference variable or with `@ViewChild`.
