### ISSUE TITLE
🐞 - MutationObserver is not defined

### ISSUE THREAD

**Issue by mohamed-rekiba** [taiga-family/ng-web-apis#524]
### Description

- Issue encountered with @ng-web-apis/mutation-observer npm package in Angular SSR causing server closure due to an exception.
- Identified problem lies within the MutationObserverService class, which is using MutationObserver instead of SafeObserver.
- Investigated the source code and discovered it already implements SafeObserver.
- Suggest updating the npm package with the latest source code to resolve the issue.

ReferenceError: MutationObserver is not defined
    at MutationObserverService.eval (/app/node_modules/.pnpm/@ng-web-apis+mutation-observer@3.1.0_@angular+core@17.3.5_rxjs@7.8.1_zone.js@0.14.4__@ng-web-_odteyczjjqgnrdfw53csgkqmv4/node_modules/@ng-web-apis/mutation-observer/fesm2015/ng-web-apis-mutation-observer.js:138:24)
    at MutationObserverService._trySubscribe (/app/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm/internal/Observable.js:37:25)
    at eval (/app/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm/internal/Observable.js:31:30)
    at errorContext (/app/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm/internal/util/errorContext.js:19:9)
    at MutationObserverService.subscribe (/app/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm/internal/Observable.js:22:9)
    at doInnerSub (/app/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm/internal/operators/mergeInternals.js:19:44)
    at outerNext (/app/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm/internal/operators/mergeInternals.js:14:57)
    at OperatorSubscriber.OperatorSubscriber._next (/app/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm/internal/operators/OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (/app/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm/internal/Subscriber.js:31:18)
    at _Observable.eval (/app/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm/internal/observable/innerFrom.js:51:24)

### Angular version

17.3.5

### Taiga UI version

3.75.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by mohamed-rekiba** [comment]
Until this problem is fixed, I've crafted the following postinstall script as a temporary solution.
```shell
#!/bin/env sh

# Fix MutationObserver is not defined issue
NODE_MODULES="node_modules"
find "$NODE_MODULES" -type f \( -name "ng-web-apis-mutation*" -o -name "mutation-observer.service*" \) | while read -r file; do
    sed -i 's/new MutationObserver/new SafeObserver/g' $file 2>/dev/null
done

exit 0
```

**Comment by samerkassem82** [comment]
Faced the same issue, as if taiga is not compabile with angular 17+? 

> Until this issue is resolved, I've crafted the following postinstall script as a temporary solution.
> 
> ```shell
> #!/bin/env sh
> 
> # Fix MutationObserver is not defined issue
> NODE_MODULES="node_modules"
> find "$NODE_MODULES" -type f \( -name "ng-web-apis-mutation*" -o -name "mutation-observer.service*" \) | while read -r file; do
>     sed -i 's/new MutationObserver/new SafeObserver/g' $file 2>/dev/null
> done
> 
> exit 0
> ```

Where do you run that?

**Comment by splincode** [comment]
Try upgrade to v4.x

**Comment by mohamed-rekiba** [comment]
> Faced the same issue, as if taiga is not compabile with angular 17+?
> 
> > Until this issue is resolved, I've crafted the following postinstall script as a temporary solution.
> > ```shell
> > #!/bin/env sh
> > 
> > # Fix MutationObserver is not defined issue
> > NODE_MODULES="node_modules"
> > find "$NODE_MODULES" -type f \( -name "ng-web-apis-mutation*" -o -name "mutation-observer.service*" \) | while read -r file; do
> >     sed -i 's/new MutationObserver/new SafeObserver/g' $file 2>/dev/null
> > done
> > 
> > exit 0
> > ```
> 
> Where do you run that?

I execute it in the `postinstall` script section of the `package.json` file

**Comment by mohamed-rekiba** [comment]
> Try upgrade to v4.x

Will check it today

**Comment by pppdns** [comment]
I'm getting the same error in SSR from `MutationObserverService`.

> Try upgrade to v4.x

While tying to update, I'm running into lots of dependency issues between `@ng-web-apis', `@types/node', NVM, available cloud versions, etc, so this is not a simple solution.

`@ng-web-apis` seems to have overly strict version dependencies that's difficult to match with other packages and Node LTS versions. It would be nice to be less restrictive regarding dependencies, especially around latest Node versions that may not have good enough support from other packages or tools.

E.g. this package even defines the minimum patch version for a `@types/node` version, but NVM doesn't support defining patch versions, only major and minor versions.

**Comment by splincode** [comment]
@pppdns could you add repo for reproduce?

**Comment by pppdns** [comment]
> Try upgrade to v4.x

I ran into an even bigger issue, TaigaUI's latest stable version (3.87) doesn't support `@ng-web-apis` v4.x.

https://github.com/taiga-family/taiga-ui/blob/v3.87.0/package.json

<img width="631" alt="Screenshot 2024-07-28 at 19 20 32" src="https://github.com/user-attachments/assets/cc585eed-fa71-4296-aa42-defecbce9d61">


There are RC versions for TaigaUI v4.x, but there's no migration guide or change log entries for version 4.
https://github.com/taiga-family/taiga-ui/blob/main/CHANGELOG.md

This means there's no easy way for us to update to TaigaUI v4.x, and without that, we can't use `@ng-web-apis` v4.x

**Comment by pppdns** [comment]
I did some more digging, the PR where this was fixed is here:
https://github.com/taiga-family/ng-web-apis/pull/350

However, this fix had only been merged into v4.x and hasn't been applied to v3.x, even though v3.x is the stable version right now, v4.x is only in RC state and not stable yet

**Comment by pppdns** [comment]
`SafeObserver` is not available in v3.x as a shared class, it's locally defined in the `intersection-observer` directive.
Which means that `MutationObserverService` can't import it.

I wanted to open a PR to fix this for v3.x but this is going to be more complicated.

I'm thinking we could just merge the code fixes from this PR to the v3.x branch and push a fix.
https://github.com/taiga-family/ng-web-apis/pull/350/files

What do you think?

**Comment by pppdns** [comment]
I created a PR to fix this exact issue without changing anything else

https://github.com/taiga-family/ng-web-apis/pull/654

**Comment by pppdns** [comment]
I created a PR to fix this exact issue without changing anything else @splincode @waterplea 

https://github.com/taiga-family/ng-web-apis/pull/654
