### ISSUE TITLE
Why is 3.2.2 tagged as latest, is that intentional?

### ISSUE THREAD

**Issue by JakobMadsen717** [taiga-family/ng-web-apis#657]
Why is 3.2.2 tagged as latest, is that intentional? I am just wondering which version is the newest?

```
C:\> npm outdated
Package                   Current  Wanted  Latest  Location
@ng-web-apis/common         4.2.0   4.2.0   3.2.2  node_modules/@ng-web-apis/common
@ng-web-apis/geolocation    4.2.0   4.2.0   3.2.2  node_modules/@ng-web-apis/geolocation
C:\> 
```

**Comment by waterplea** [comment]
@splincode could you take a look, please?

**Comment by RyannGalea** [comment]
![image](https://github.com/user-attachments/assets/fe02e8e2-bd3f-42bc-97c1-de975877d40d)

Has been confusing here too.
